export const fakeData = {
  error: false,
  msg: "SUCCESS",
  data: {
    topLoss: {
      _id: "64c3a365657deecc75f0a1bd",
      BatchDate: "28/07/2023",
      DayInWeek: 5,
      Shift: 2,
      StepLossDetails: [
        {
          _id: "64c3a365657deecc75f0a1ff",
          BatchID: ["233052501"],
          BatchDate: "28/07/2023",
          CUCCode: ["68688437"],
          DayInWeek: 5,
          Shift: 2,
          Loss: -25,
          Step: "BCTPremix",
          createdAt: "2023-07-28T11:15:49.141Z",
          updatedAt: "2023-07-28T11:16:19.714Z",
          __v: 0,
        },
        {
          _id: "64c3a365657deecc75f0a201",
          BatchID: ["233052501"],
          BatchDate: "28/07/2023",
          CUCCode: ["68688437"],
          DayInWeek: 5,
          Shift: 2,
          Loss: -2,
          Step: "CapB_1",
          createdAt: "2023-07-28T11:15:49.143Z",
          updatedAt: "2023-07-28T11:16:19.731Z",
          __v: 0,
        },
        {
          _id: "64c3a365657deecc75f0a207",
          BatchID: ["233052501"],
          BatchDate: "28/07/2023",
          CUCCode: ["68688437"],
          DayInWeek: 5,
          Shift: 2,
          Loss: -0.36668333333333325,
          Step: "Caustic_ft1_1",
          createdAt: "2023-07-28T11:15:49.150Z",
          updatedAt: "2023-07-28T11:16:19.735Z",
          __v: 0,
        },
        {
          _id: "64c3a365657deecc75f0a205",
          BatchID: ["233052501"],
          BatchDate: "28/07/2023",
          CUCCode: ["68688437"],
          DayInWeek: 5,
          Shift: 2,
          Loss: -1,
          Step: "Caustic_ft_1",
          createdAt: "2023-07-28T11:15:49.147Z",
          updatedAt: "2023-07-28T11:16:19.738Z",
          __v: 0,
        },
        {
          _id: "64c3a365657deecc75f0a209",
          BatchID: ["233052501"],
          BatchDate: "28/07/2023",
          CUCCode: ["68688437"],
          DayInWeek: 5,
          Shift: 2,
          Loss: 0.4832000000000001,
          Step: "Chlorwater_1",
          createdAt: "2023-07-28T11:15:49.152Z",
          updatedAt: "2023-07-28T11:16:19.741Z",
          __v: 0,
        },
        {
          _id: "64c3a365657deecc75f0a20b",
          BatchID: ["233052501"],
          BatchDate: "28/07/2023",
          CUCCode: ["68688437"],
          DayInWeek: 5,
          Shift: 2,
          Loss: 0,
          Step: "Cooling_1",
          createdAt: "2023-07-28T11:15:49.154Z",
          updatedAt: "2023-07-28T11:16:19.744Z",
          __v: 0,
        },
        {
          _id: "64c3a365657deecc75f0a20d",
          BatchID: ["233052501"],
          BatchDate: "28/07/2023",
          CUCCode: ["68688437"],
          DayInWeek: 5,
          Shift: 2,
          Loss: 0.5339666666666667,
          Step: "Cooling_2",
          createdAt: "2023-07-28T11:15:49.157Z",
          updatedAt: "2023-07-28T11:16:19.748Z",
          __v: 0,
        },
        {
          _id: "64c3a365657deecc75f0a222",
          BatchID: ["233052501"],
          BatchDate: "28/07/2023",
          CUCCode: ["68688437"],
          DayInWeek: 5,
          Shift: 2,
          Loss: 22.166316666666667,
          Step: "Discharge_1",
          createdAt: "2023-07-28T11:15:49.201Z",
          updatedAt: "2023-07-28T11:16:19.752Z",
          __v: 0,
        },
        {
          _id: "64c3a365657deecc75f0a224",
          BatchID: ["233052501"],
          BatchDate: "28/07/2023",
          CUCCode: ["68688437"],
          DayInWeek: 5,
          Shift: 2,
          Loss: -0.20003333333333329,
          Step: "Las_1",
          createdAt: "2023-07-28T11:15:49.205Z",
          updatedAt: "2023-07-28T11:16:19.756Z",
          __v: 0,
        },
        {
          _id: "64c3a365657deecc75f0a213",
          BatchID: ["233052501"],
          BatchDate: "28/07/2023",
          CUCCode: ["68688437"],
          DayInWeek: 5,
          Shift: 2,
          Loss: 0,
          Step: "PAS_1",
          createdAt: "2023-07-28T11:15:49.166Z",
          updatedAt: "2023-07-28T11:16:19.758Z",
          __v: 0,
        },
        {
          _id: "64c3a365657deecc75f0a203",
          BatchID: ["233052501"],
          BatchDate: "28/07/2023",
          CUCCode: ["68688437"],
          DayInWeek: 5,
          Shift: 2,
          Loss: 0,
          Step: "POLYOX_1",
          createdAt: "2023-07-28T11:15:49.145Z",
          updatedAt: "2023-07-28T11:16:19.760Z",
          __v: 0,
        },
        {
          _id: "64c3a365657deecc75f0a215",
          BatchID: ["233052501"],
          BatchDate: "28/07/2023",
          CUCCode: ["68688437"],
          DayInWeek: 5,
          Shift: 2,
          Loss: 7.7371333333333325,
          Step: "QCcheck_1",
          createdAt: "2023-07-28T11:15:49.169Z",
          updatedAt: "2023-07-28T11:16:19.762Z",
          __v: 0,
        },
        {
          _id: "64c3a365657deecc75f0a21b",
          BatchID: ["233052501"],
          BatchDate: "28/07/2023",
          CUCCode: ["68688437"],
          DayInWeek: 5,
          Shift: 2,
          Loss: 0,
          Step: "SLES1EO_Tanfram_1",
          createdAt: "2023-07-28T11:15:49.180Z",
          updatedAt: "2023-07-28T11:16:19.764Z",
          __v: 0,
        },
        {
          _id: "64c3a365657deecc75f0a217",
          BatchID: ["233052501"],
          BatchDate: "28/07/2023",
          CUCCode: ["68688437"],
          DayInWeek: 5,
          Shift: 2,
          Loss: 0,
          Step: "Sles1_1",
          createdAt: "2023-07-28T11:15:49.172Z",
          updatedAt: "2023-07-28T11:16:19.820Z",
          __v: 0,
        },
        {
          _id: "64c3a365657deecc75f0a21d",
          BatchID: ["233052501"],
          BatchDate: "28/07/2023",
          CUCCode: ["68688437"],
          DayInWeek: 5,
          Shift: 2,
          Loss: -18.504,
          Step: "Waiting",
          createdAt: "2023-07-28T11:15:49.182Z",
          updatedAt: "2023-07-28T11:16:19.839Z",
          __v: 0,
        },
        {
          _id: "64c3a365657deecc75f0a219",
          BatchID: ["233052501"],
          BatchDate: "28/07/2023",
          CUCCode: ["68688437"],
          DayInWeek: 5,
          Shift: 2,
          Loss: -1.4,
          Step: "perfume_1",
          createdAt: "2023-07-28T11:15:49.174Z",
          updatedAt: "2023-07-28T11:16:19.717Z",
          __v: 0,
        },
        {
          _id: "64c3a365657deecc75f0a21f",
          BatchID: ["233052501"],
          BatchDate: "28/07/2023",
          CUCCode: ["68688437"],
          DayInWeek: 5,
          Shift: 2,
          Loss: 19.53308333333333,
          Step: "premix_1",
          createdAt: "2023-07-28T11:15:49.183Z",
          updatedAt: "2023-07-28T11:16:19.720Z",
          __v: 0,
        },
      ],
      createdAt: "2023-07-28T11:15:49.042Z",
      updatedAt: "2023-07-28T11:16:19.863Z",
      __v: 0,
    },
    masterDataInfo: [
      {
        Mixer: "MX_1501",
        ProductCode: 68195812,
        Name: "LEMON00(GR130CAPB)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 5,
        Las_1: 5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 1,
        sles_1eo: 3,
        Sles1_1: 3,
        SLES1EO_Tanfram_1: 3,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 0,
        capb: 3.2,
        CapB_1: 3.2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 1,
        perfume: 1.5,
        perfume_1: 1.5,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 11,
        discharging: 11,
      },
      {
        Mixer: "MX_1501",
        ProductCode: 67909220,
        Name: "LEMON00(SAMURAI)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 6.5,
        Las_1: 6.5,
        naoh: 2,
        Caustic_ft_1: 2,
        Caustic_ft1_1: 2,
        rm_dmdm: 1,
        sles_1eo: 4.1,
        Sles1_1: 4.1,
        SLES1EO_Tanfram_1: 4.1,
        premixer: 3.2,
        premix_1: 5,
        sles_3eo: 0,
        capb: 3,
        CapB_1: 3,
        cooling: 1,
        Cooling_1: 1,
        Cooling_2: 1,
        ph: 1,
        perfume: 1.5,
        perfume_1: 1.5,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 12,
        discharging: 11,
      },
      {
        Mixer: "MX_1502",
        ProductCode: 69766939,
        Name: "CUC SUNLIGHT DWL CINNAMON (HIKING)",
        chlorwater: 10,
        Chlorwater_1: 10,
        "ADD Manuchau": 0,
        Las: 0,
        Las_1: 0,
        naoh: 1.2,
        Caustic_ft_1: 1.2,
        Caustic_ft1_1: 1.2,
        rm_dmdm: 2,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 4.5,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0.5,
        Cooling_1: 0.5,
        Cooling_2: 0.5,
        ph: 0,
        perfume: 2,
        perfume_1: 2,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 11,
        discharging: 11,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "67359517",
        Name: "0ANTIBAC",
        chlorwater: 8,
        Chlorwater_1: 8,
        "ADD Manuchau": 0,
        Las: 4,
        Las_1: 4,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 8.5,
        Sles1_1: 8.5,
        SLES1EO_Tanfram_1: 8.5,
        premixer: 3,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 1,
        Cooling_1: 1,
        Cooling_2: 1,
        ph: 1,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 12,
        discharging: 12,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "67364985",
        Name: "NATURE0VN0(HIKING)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 4,
        Las_1: 4,
        naoh: 2,
        Caustic_ft_1: 2,
        Caustic_ft1_1: 2,
        rm_dmdm: 0,
        sles_1eo: 2.5,
        Sles1_1: 2.5,
        SLES1EO_Tanfram_1: 2.5,
        premixer: 3,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 1,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 12,
        discharging: 12,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "67901896",
        Name: "SUNLIGHT0DWL0GENTLE0VN0(HIKING0Y2)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 4,
        Las_1: 4,
        naoh: 2,
        Caustic_ft_1: 2,
        Caustic_ft1_1: 2,
        rm_dmdm: 0,
        sles_1eo: 2.5,
        Sles1_1: 2.5,
        SLES1EO_Tanfram_1: 2.5,
        premixer: 3,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 1,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 12,
        discharging: 12,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68282794",
        Name: "NATURE0(GR13CAPB)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 5,
        Las_1: 5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 1,
        sles_1eo: 3,
        Sles1_1: 3,
        SLES1EO_Tanfram_1: 3,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 0,
        capb: 3,
        CapB_1: 3,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 1,
        perfume: 1.5,
        perfume_1: 1.5,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 11,
        discharging: 11,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68282795",
        Name: "GREENTEA00(GR130CAPB)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 5,
        Las_1: 5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 1,
        sles_1eo: 3,
        Sles1_1: 3,
        SLES1EO_Tanfram_1: 3,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 0,
        capb: 3,
        CapB_1: 3,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 1,
        perfume: 1.5,
        perfume_1: 1.5,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 11,
        discharging: 11,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68349970",
        Name: "SOOTHING0",
        chlorwater: 8,
        Chlorwater_1: 8,
        "ADD Manuchau": 0,
        Las: 0,
        Las_1: 0,
        naoh: null,
        Caustic_ft_1: null,
        Caustic_ft1_1: null,
        rm_dmdm: null,
        sles_1eo: 9,
        Sles1_1: 9,
        SLES1EO_Tanfram_1: 9,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 0,
        capb: 3,
        CapB_1: 3,
        cooling: 1,
        Cooling_1: 1,
        Cooling_2: 1,
        ph: 1.3,
        perfume: 1.5,
        perfume_1: 1.5,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 11,
        discharging: 11,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "21109346",
        Name: "ANTI0ODOUR",
        chlorwater: 8,
        Chlorwater_1: 8,
        "ADD Manuchau": 0,
        Las: 6,
        Las_1: 6,
        naoh: 2,
        Caustic_ft_1: 2,
        Caustic_ft1_1: 2,
        rm_dmdm: 1,
        sles_1eo: 4.5,
        Sles1_1: 4.5,
        SLES1EO_Tanfram_1: 4.5,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 1,
        Cooling_1: 1,
        Cooling_2: 1,
        ph: 1,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 12,
        discharging: 12,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "20269489",
        Name: "LEMON0(SQUASH)0",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 4,
        Las_1: 4,
        naoh: 2,
        Caustic_ft_1: 2,
        Caustic_ft1_1: 2,
        rm_dmdm: 0,
        sles_1eo: 2.5,
        Sles1_1: 2.5,
        SLES1EO_Tanfram_1: 2.5,
        premixer: 3,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 1,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 12,
        discharging: 12,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "67668612",
        Name: "LIME0GHANA",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 4,
        Las_1: 4,
        naoh: 2,
        Caustic_ft_1: 2,
        Caustic_ft1_1: 2,
        rm_dmdm: 0,
        sles_1eo: 2.5,
        Sles1_1: 2.5,
        SLES1EO_Tanfram_1: 2.5,
        premixer: 3,
        premix_1: 5,
        sles_3eo: 0,
        capb: 3,
        CapB_1: 3,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 1,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 12,
        discharging: 12,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "21085594",
        Name: "0LIME0(PETRONAS)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 4,
        Las_1: 4,
        naoh: 2,
        Caustic_ft_1: 2,
        Caustic_ft1_1: 2,
        rm_dmdm: 0,
        sles_1eo: 2.5,
        Sles1_1: 2.5,
        SLES1EO_Tanfram_1: 2.5,
        premixer: 3,
        premix_1: 5,
        sles_3eo: 0,
        capb: 3,
        CapB_1: 3,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 1,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 12,
        discharging: 12,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "21085595",
        Name: "LEMON0(PETRONAS)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 6.5,
        Las_1: 6.5,
        naoh: 2,
        Caustic_ft_1: 2,
        Caustic_ft1_1: 2,
        rm_dmdm: 0,
        sles_1eo: 4,
        Sles1_1: 4,
        SLES1EO_Tanfram_1: 4,
        premixer: 3,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 1,
        Cooling_1: 1,
        Cooling_2: 1,
        ph: 1,
        perfume: 1.5,
        perfume_1: 1.5,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 11,
        discharging: 11,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "21077177",
        Name: "0GEL0LEMON0(ARCHERY)0",
        chlorwater: 4,
        Chlorwater_1: 4,
        "ADD Manuchau": 0,
        Las: 3,
        Las_1: 3,
        naoh: 3,
        Caustic_ft_1: 3,
        Caustic_ft1_1: 3,
        rm_dmdm: 1,
        sles_1eo: 10,
        Sles1_1: 10,
        SLES1EO_Tanfram_1: 10,
        premixer: 1,
        premix_1: 5,
        sles_3eo: 0,
        capb: 2,
        CapB_1: 2,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 15,
        discharging: 15,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "21077178",
        Name: "GEL0LIME0(ARCHERY)",
        chlorwater: 4,
        Chlorwater_1: 4,
        "ADD Manuchau": 0,
        Las: 3,
        Las_1: 3,
        naoh: 3,
        Caustic_ft_1: 3,
        Caustic_ft1_1: 3,
        rm_dmdm: 1,
        sles_1eo: 10,
        Sles1_1: 10,
        SLES1EO_Tanfram_1: 10,
        premixer: 1,
        premix_1: 5,
        sles_3eo: 0,
        capb: 2,
        CapB_1: 2,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 15,
        discharging: 15,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "21100522",
        Name: "0GEL0GREEN0TEA",
        chlorwater: 4,
        Chlorwater_1: 4,
        "ADD Manuchau": 0,
        Las: 3,
        Las_1: 3,
        naoh: 3,
        Caustic_ft_1: 3,
        Caustic_ft1_1: 3,
        rm_dmdm: 1,
        sles_1eo: 10,
        Sles1_1: 10,
        SLES1EO_Tanfram_1: 10,
        premixer: 1,
        premix_1: 5,
        sles_3eo: 0,
        capb: 2,
        CapB_1: 2,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 15,
        discharging: 15,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "21100523",
        Name: "GEL0LEMON",
        chlorwater: 4,
        Chlorwater_1: 4,
        "ADD Manuchau": 0,
        Las: 3,
        Las_1: 3,
        naoh: 3,
        Caustic_ft_1: 3,
        Caustic_ft1_1: 3,
        rm_dmdm: 1,
        sles_1eo: 10,
        Sles1_1: 10,
        SLES1EO_Tanfram_1: 10,
        premixer: 1,
        premix_1: 5,
        sles_3eo: 0,
        capb: 2,
        CapB_1: 2,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 15,
        discharging: 15,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "67021629",
        Name: "LEMON0(HIJUMP0CHINA)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 5,
        Las_1: 5,
        naoh: 2,
        Caustic_ft_1: 2,
        Caustic_ft1_1: 2,
        rm_dmdm: 0,
        sles_1eo: 4,
        Sles1_1: 4,
        SLES1EO_Tanfram_1: 4,
        premixer: 4,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 1,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 12,
        discharging: 12,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "67021633",
        Name: "LEMON0(HIJUMP0CHINA)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 5,
        Las_1: 5,
        naoh: 2,
        Caustic_ft_1: 2,
        Caustic_ft1_1: 2,
        rm_dmdm: 0,
        sles_1eo: 4,
        Sles1_1: 4,
        SLES1EO_Tanfram_1: 4,
        premixer: 4,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 1,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 12,
        discharging: 12,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "67021648",
        Name: "NATURE0(HIJUMP0CHINA)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 5,
        Las_1: 5,
        naoh: 2,
        Caustic_ft_1: 2,
        Caustic_ft1_1: 2,
        rm_dmdm: 0,
        sles_1eo: 4,
        Sles1_1: 4,
        SLES1EO_Tanfram_1: 4,
        premixer: 4,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 1,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 12,
        discharging: 12,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68386813",
        Name: "0SURF0LIME(UI)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 5,
        Las_1: 5,
        naoh: 2,
        Caustic_ft_1: 2,
        Caustic_ft1_1: 2,
        rm_dmdm: 0,
        sles_1eo: 4,
        Sles1_1: 4,
        SLES1EO_Tanfram_1: 4,
        premixer: 4,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 1,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 12,
        discharging: 12,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68386814",
        Name: "SURF0LEMON0(UI)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 5,
        Las_1: 5,
        naoh: 2,
        Caustic_ft_1: 2,
        Caustic_ft1_1: 2,
        rm_dmdm: 0,
        sles_1eo: 4,
        Sles1_1: 4,
        SLES1EO_Tanfram_1: 4,
        premixer: 4,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 1,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 12,
        discharging: 12,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "67746969",
        Name: "SURF0DWL0LEMON",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 5,
        Las_1: 5,
        naoh: 2,
        Caustic_ft_1: 2,
        Caustic_ft1_1: 2,
        rm_dmdm: 0,
        sles_1eo: 4,
        Sles1_1: 4,
        SLES1EO_Tanfram_1: 4,
        premixer: 4,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 1,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 12,
        discharging: 12,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68494407",
        Name: "0SURF0LEMON00(TITAN)",
        chlorwater: 8,
        Chlorwater_1: 8,
        "ADD Manuchau": 0,
        Las: 5,
        Las_1: 5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 1,
        sles_1eo: 3,
        Sles1_1: 3,
        SLES1EO_Tanfram_1: 3,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 0,
        capb: 3,
        CapB_1: 3,
        cooling: 1,
        Cooling_1: 1,
        Cooling_2: 1,
        ph: 0.5,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 11,
        discharging: 11,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68835436",
        Name: "SURF0DWL0Green0Tea0&0Pandan",
        chlorwater: 8.5,
        Chlorwater_1: 8.5,
        "ADD Manuchau": 0,
        Las: 4.5,
        Las_1: 4.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 1,
        sles_1eo: 2.5,
        Sles1_1: 2.5,
        SLES1EO_Tanfram_1: 2.5,
        premixer: 4,
        premix_1: 5,
        sles_3eo: 0,
        capb: 3,
        CapB_1: 3,
        cooling: 1,
        Cooling_1: 1,
        Cooling_2: 1,
        ph: 1,
        perfume: 1.5,
        perfume_1: 1.5,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 11,
        discharging: 11,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "21001980",
        Name: "Green",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 0,
        Las_1: 0,
        naoh: 1,
        Caustic_ft_1: 1,
        Caustic_ft1_1: 1,
        rm_dmdm: 2,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 4,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 0,
        perfume: 2,
        perfume_1: 2,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 11,
        discharging: 11,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "67621459",
        Name: "Green0(0NON0BIT0)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 0,
        Las_1: 0,
        naoh: 1,
        Caustic_ft_1: 1,
        Caustic_ft1_1: 1,
        rm_dmdm: 2,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 4,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 0,
        perfume: 2,
        perfume_1: 2,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 11,
        discharging: 11,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68632365",
        Name: "Green-Linkinpark",
        chlorwater: 9,
        Chlorwater_1: 9,
        "ADD Manuchau": 0,
        Las: 0,
        Las_1: 0,
        naoh: 1.2,
        Caustic_ft_1: 1.2,
        Caustic_ft1_1: 1.2,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 4.2,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0.5,
        Cooling_1: 0.5,
        Cooling_2: 0.5,
        ph: 0,
        perfume: 0,
        perfume_1: 0,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 11,
        discharging: 11,
      },
      {
        Mixer: "MX_1501",
        ProductCode: 69636786,
        Name: "FC CINANMON",
        chlorwater: 10,
        Chlorwater_1: 10,
        "ADD Manuchau": 0,
        Las: 0,
        Las_1: 0,
        naoh: 1.2,
        Caustic_ft_1: 1.2,
        Caustic_ft1_1: 1.2,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 4.5,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0.5,
        Cooling_1: 0.5,
        Cooling_2: 0.5,
        ph: 0,
        perfume: 0,
        perfume_1: 0,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 11,
        discharging: 11,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "21001981",
        Name: "Pink",
        chlorwater: 10,
        Chlorwater_1: 10,
        "ADD Manuchau": 0,
        Las: 0,
        Las_1: 0,
        naoh: 1.2,
        Caustic_ft_1: 1.2,
        Caustic_ft1_1: 1.2,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 4.5,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0.5,
        Cooling_1: 0.5,
        Cooling_2: 0.5,
        ph: 0,
        perfume: 0,
        perfume_1: 0,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 11,
        discharging: 11,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "21120829",
        Name: "Gold",
        chlorwater: 10,
        Chlorwater_1: 10,
        "ADD Manuchau": 0,
        Las: 0,
        Las_1: 0,
        naoh: 1.2,
        Caustic_ft_1: 1.2,
        Caustic_ft1_1: 1.2,
        rm_dmdm: 2,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 4.5,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0.5,
        Cooling_1: 0.5,
        Cooling_2: 0.5,
        ph: 0,
        perfume: 2,
        perfume_1: 2,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 11,
        discharging: 11,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68359259",
        Name: "Lemongrass0(0Manuchao)",
        chlorwater: 10,
        Chlorwater_1: 10,
        "ADD Manuchau": 10,
        Las: 0,
        Las_1: 0,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0.5,
        Cooling_1: 0.5,
        Cooling_2: 0.5,
        ph: 1.5,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 11,
        discharging: 11,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "67686535",
        Name: "White0(NON0BIT)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 0,
        Las_1: 0,
        naoh: 1,
        Caustic_ft_1: 1,
        Caustic_ft1_1: 1,
        rm_dmdm: 2,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 4,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 0,
        perfume: 2,
        perfume_1: 2,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 11,
        discharging: 11,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68359260",
        Name: "Purre0(Manuchau)",
        chlorwater: 9,
        Chlorwater_1: 9,
        "ADD Manuchau": 10,
        Las: 0,
        Las_1: 0,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0.5,
        Cooling_1: 0.5,
        Cooling_2: 0.5,
        ph: 1.5,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 15,
        discharging: 15,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68542849",
        Name: "DECREASER0(HORECA)",
        chlorwater: 8.5,
        Chlorwater_1: 8.5,
        "ADD Manuchau": 0,
        Las: 0,
        Las_1: 0,
        naoh: 1,
        Caustic_ft_1: 1,
        Caustic_ft1_1: 1,
        rm_dmdm: 2,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 4.5,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 11,
        discharging: 11,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68611370",
        Name: "LIFEBUOY0FC0(BACON)00",
        chlorwater: 12,
        Chlorwater_1: 12,
        "ADD Manuchau": 0,
        Las: 0,
        Las_1: 0,
        naoh: 5,
        Caustic_ft_1: 5,
        Caustic_ft1_1: 5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 0,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 0,
        perfume: 0,
        perfume_1: 0,
        "ADD - Manual": 0,
        uniformity: 0,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 14,
        discharging: 14,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68706033",
        Name: "LIFEBUOY0MPP0SPRAY",
        chlorwater: 12,
        Chlorwater_1: 12,
        "ADD Manuchau": 0,
        Las: 0,
        Las_1: 0,
        naoh: 0,
        Caustic_ft_1: 0,
        Caustic_ft1_1: 0,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 4,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 12,
        discharging: 12,
      },
      {
        Mixer: "MX_1501",
        ProductCode: 67690729,
        Name: "HW0SHY+",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 24,
        capb: 2,
        CapB_1: 2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68168655",
        Name: "COMFORT0PINK",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 24,
        capb: 2,
        CapB_1: 2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68818992",
        Name: "COMFORT0PINK0(BIT)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 24,
        capb: 2,
        CapB_1: 2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68274005",
        Name: "SURF0LIQUID0",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 24,
        capb: 2,
        CapB_1: 2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68274775",
        Name: "COLOR0CARE0",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 24,
        capb: 2,
        CapB_1: 2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: 68737064,
        Name: "TL0CLR0CARE0(BIT)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 24,
        capb: 2,
        CapB_1: 2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68274778",
        Name: "GENTLE",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 24,
        capb: 2,
        CapB_1: 2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: 68422600,
        Name: "SURF0FLORAL",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 24,
        capb: 2,
        CapB_1: 2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68422601",
        Name: "SURF0EMERAL",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 24,
        capb: 2,
        CapB_1: 2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68465921",
        Name: "SURF03IN10PREMIUM",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 24,
        capb: 2,
        CapB_1: 2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68688437",
        Name: "SURF0FLORAL0(THANOS0Y2)",
        chlorwater: 8,
        Chlorwater_1: 8,
        "ADD Manuchau": 0,
        Las: 3,
        Las_1: 3,
        naoh: 1,
        Caustic_ft_1: 1,
        Caustic_ft1_1: 1,
        rm_dmdm: 2,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 3.5,
        premix_1: 5,
        sles_3eo: 21,
        capb: 2,
        CapB_1: 2,
        cooling: 0.5,
        Cooling_1: 0.5,
        Cooling_2: 0.5,
        ph: 0.5,
        perfume: 1.7,
        perfume_1: 1.7,
        "ADD - Manual": 0,
        uniformity: 37,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: 68688438,
        Name: "SURF0EMERAL0(THANOS0Y2)0",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 24,
        capb: 2,
        CapB_1: 2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: 69564958,
        Name: "SURF0EMERAL0(THANOS0Y2)0",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 24,
        capb: 2,
        CapB_1: 2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: 68688439,
        Name: "SURF0DETERGENT0(THANOS0Y20)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 24,
        capb: 2,
        CapB_1: 2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68718614",
        Name: "GENTLE0BABY0",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 24,
        capb: 2,
        CapB_1: 2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68274776",
        Name: "COMFORT0GOLD0",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 24,
        capb: 2,
        CapB_1: 2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68733473",
        Name: "COMFORT0GOLD0(BIT)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 24,
        capb: 2,
        CapB_1: 2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68737065",
        Name: "PURPLE",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 24,
        capb: 2,
        CapB_1: 2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68737066",
        Name: "PINK0",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 24,
        capb: 2,
        CapB_1: 2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: 67690732,
        Name: "0Front0load00(B2B0OIT)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 2.5,
        premix_1: 5,
        sles_3eo: 20,
        capb: 0,
        CapB_1: 0,
        cooling: 4,
        Cooling_1: 4,
        Cooling_2: 4,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 5,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 13,
        discharging: 13,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "67847031",
        Name: "CUC0COMFORT0LIQ0DETERGENT0BELLE0VN0PINK",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 2.5,
        premix_1: 5,
        sles_3eo: 20,
        capb: 0,
        CapB_1: 0,
        cooling: 4,
        Cooling_1: 4,
        Cooling_2: 4,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 5,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 13,
        discharging: 13,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "67895549",
        Name: "BELLE0PURPLE",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 2.5,
        premix_1: 5,
        sles_3eo: 20,
        capb: 0,
        CapB_1: 0,
        cooling: 4,
        Cooling_1: 4,
        Cooling_2: 4,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 5,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 13,
        discharging: 13,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68274777",
        Name: "0TL0CORE",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 2.5,
        premix_1: 5,
        sles_3eo: 20,
        capb: 0,
        CapB_1: 0,
        cooling: 4,
        Cooling_1: 4,
        Cooling_2: 4,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 5,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 13,
        discharging: 13,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68275495",
        Name: "0TL00DEO0FRESH",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 2.5,
        premix_1: 5,
        sles_3eo: 20,
        capb: 0,
        CapB_1: 0,
        cooling: 4,
        Cooling_1: 4,
        Cooling_2: 4,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 5,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 13,
        discharging: 13,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68309595",
        Name: "FL0CLR0CARE0(GAIA)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 2.5,
        premix_1: 5,
        sles_3eo: 20,
        capb: 0,
        CapB_1: 0,
        cooling: 4,
        Cooling_1: 4,
        Cooling_2: 4,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 5,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 13,
        discharging: 13,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68392444",
        Name: "FL0COLOR0CARE0(HERA)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 2.5,
        premix_1: 5,
        sles_3eo: 20,
        capb: 0,
        CapB_1: 0,
        cooling: 4,
        Cooling_1: 4,
        Cooling_2: 4,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 5,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 13,
        discharging: 13,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68733471",
        Name: "TL0CORE0(BIT)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 2.5,
        premix_1: 5,
        sles_3eo: 20,
        capb: 0,
        CapB_1: 0,
        cooling: 4,
        Cooling_1: 4,
        Cooling_2: 4,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 5,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 13,
        discharging: 13,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68733472",
        Name: "FL0CLR0CARE0(HERA-BIT)",
        chlorwater: 9.5,
        Chlorwater_1: 9.5,
        "ADD Manuchau": 0,
        Las: 4,
        Las_1: 4,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 1.8,
        premix_1: 5,
        sles_3eo: 10,
        capb: 0,
        CapB_1: 0,
        cooling: 4,
        Cooling_1: 4,
        Cooling_2: 4,
        ph: 0,
        perfume: 0,
        perfume_1: 0,
        "ADD - Manual": 0,
        uniformity: 5,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: 68733474,
        Name: "FL0CLR0CARE0(GAIA-BIT)",
        chlorwater: 9,
        Chlorwater_1: 9,
        "ADD Manuchau": 0,
        Las: 4,
        Las_1: 4,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 1.5,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 0,
        premix_1: 5,
        sles_3eo: 9,
        capb: 0,
        CapB_1: 0,
        cooling: 8,
        Cooling_1: 8,
        Cooling_2: 8,
        ph: 0,
        perfume: 0,
        perfume_1: 0,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "67026750",
        Name: "SURF0LIQ0(MANILA)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 24,
        capb: 2,
        CapB_1: 2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: 68348767,
        Name: "SURF0DETERGENT0(LUNA)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 24,
        capb: 2,
        CapB_1: 2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68665009",
        Name: "SURF0CHERRY00(HYDRA)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 24,
        capb: 2,
        CapB_1: 2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68665010",
        Name: "SURF00ROSE0(HYDRA)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 24,
        capb: 2,
        CapB_1: 2,
        cooling: 2,
        Cooling_1: 2,
        Cooling_2: 2,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 10,
        discharging: 10,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "67776701",
        Name: "CF0DTRGNT0PINK0(BELLE0PH0Y2)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 2.5,
        premix_1: 5,
        sles_3eo: 20,
        capb: 0,
        CapB_1: 0,
        cooling: 4,
        Cooling_1: 4,
        Cooling_2: 4,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 5,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 13,
        discharging: 13,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "67776702",
        Name: "CF0DTRGNT0BLUE0(BELLE0PH0Y2)",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 2.5,
        premix_1: 5,
        sles_3eo: 20,
        capb: 0,
        CapB_1: 0,
        cooling: 4,
        Cooling_1: 4,
        Cooling_2: 4,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 5,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 13,
        discharging: 13,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68225282",
        Name: "BREEZE0CORE",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 2.5,
        premix_1: 5,
        sles_3eo: 20,
        capb: 0,
        CapB_1: 0,
        cooling: 4,
        Cooling_1: 4,
        Cooling_2: 4,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 5,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 13,
        discharging: 13,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "67682596",
        Name: "BREEZE0ROSE0GOLD",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 2.5,
        premix_1: 5,
        sles_3eo: 20,
        capb: 0,
        CapB_1: 0,
        cooling: 4,
        Cooling_1: 4,
        Cooling_2: 4,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 5,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 13,
        discharging: 13,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68541132",
        Name: "0BREEZE0ANTIBACTERIA",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 2.5,
        premix_1: 5,
        sles_3eo: 20,
        capb: 0,
        CapB_1: 0,
        cooling: 4,
        Cooling_1: 4,
        Cooling_2: 4,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 5,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 13,
        discharging: 13,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "32003460",
        Name: "CUC0BREEZE0EXCEL0LIQ0BIKINIW20PH",
        chlorwater: 7,
        Chlorwater_1: 7,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 2.5,
        premix_1: 5,
        sles_3eo: 20,
        capb: 0,
        CapB_1: 0,
        cooling: 4,
        Cooling_1: 4,
        Cooling_2: 4,
        ph: 0,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 0,
        uniformity: 5,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 13,
        discharging: 13,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "67768486",
        Name: "FRONTLOAD0UI0(ANZ0OIT)",
        chlorwater: 8.5,
        Chlorwater_1: 8.5,
        "ADD Manuchau": 0,
        Las: 3.8,
        Las_1: 3.8,
        naoh: 1.5,
        Caustic_ft_1: 1.5,
        Caustic_ft1_1: 1.5,
        rm_dmdm: 1.5,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 0,
        premix_1: 5,
        sles_3eo: 7,
        capb: 0,
        CapB_1: 0,
        cooling: 10,
        Cooling_1: 10,
        Cooling_2: 10,
        ph: 0,
        perfume: 0,
        perfume_1: 0,
        "ADD - Manual": 0,
        uniformity: 5,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: null,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 11,
        discharging: 11,
      },
      {
        Mixer: "MX_1501",
        ProductCode: "68462792",
        Name: "LAUNDRY0SANITIZER",
        chlorwater: 0,
        Chlorwater_1: 0,
        "ADD Manuchau": 0,
        Las: 0,
        Las_1: 0,
        naoh: 0,
        Caustic_ft_1: 0,
        Caustic_ft1_1: 0,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 0,
        premix_1: 5,
        sles_3eo: 0,
        capb: 0,
        CapB_1: 0,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 0,
        perfume: 0,
        perfume_1: 0,
        "ADD - Manual": 0,
        uniformity: 0,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 0,
        discharging: 0,
      },
      {
        Mixer: "MX_1501",
        ProductCode: 69641444,
        Name: "OMO0GOLD0(JUNO)",
        chlorwater: 7.5,
        Chlorwater_1: 7.5,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1,
        Caustic_ft_1: 1,
        Caustic_ft1_1: 1,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 3.5,
        premix_1: 5,
        sles_3eo: 22,
        capb: 0,
        CapB_1: 0,
        cooling: 0.5,
        Cooling_1: 0.5,
        Cooling_2: 0.5,
        ph: 1,
        perfume: 2.8,
        perfume_1: 2.8,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 12,
        discharging: 12,
      },
      {
        Mixer: "MX_1501",
        ProductCode: 69641443,
        Name: "OMO CF G0LD (JUNO)",
        chlorwater: 7.5,
        Chlorwater_1: 7.5,
        "ADD Manuchau": 0,
        Las: 2.5,
        Las_1: 2.5,
        naoh: 1,
        Caustic_ft_1: 1,
        Caustic_ft1_1: 1,
        rm_dmdm: 0,
        sles_1eo: 0,
        Sles1_1: 0,
        SLES1EO_Tanfram_1: 0,
        premixer: 3.5,
        premix_1: 5,
        sles_3eo: 22,
        capb: 0,
        CapB_1: 0,
        cooling: 0.5,
        Cooling_1: 0.5,
        Cooling_2: 0.5,
        ph: 1,
        perfume: 2.8,
        perfume_1: 2.8,
        "ADD - Manual": 0,
        uniformity: 3,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 0,
        POLYOX: 0,
        POLYOX_1: 0,
        BCTPremix: 25,
        Discharge_1: 12,
        discharging: 12,
      },
      {
        Mixer: "MX_1501",
        ProductCode: 69668301,
        Name: "DW SWIMMING",
        chlorwater: 6,
        Chlorwater_1: 6,
        "ADD Manuchau": null,
        Las: null,
        Las_1: null,
        naoh: 4,
        Caustic_ft_1: 4,
        Caustic_ft1_1: 4,
        rm_dmdm: 2,
        sles_1eo: 4,
        Sles1_1: 4,
        SLES1EO_Tanfram_1: 4,
        premixer: 5,
        premix_1: 5,
        sles_3eo: 0,
        capb: 4,
        CapB_1: 4,
        cooling: 0,
        Cooling_1: 0,
        Cooling_2: 0,
        ph: 5,
        perfume: 1,
        perfume_1: 1,
        "ADD - Manual": 5,
        uniformity: 5,
        qc_check: 5,
        QCcheck_1: 5,
        Waiting: 0,
        PAS_1: 4,
        POLYOX: 3,
        POLYOX_1: 3,
        BCTPremix: 25,
        Discharge_1: 11,
        discharging: 11,
      },
    ],
  },
};
